spring:
  application:
    name: goods-producer-bot

bot:
  goods:
    name: goodsProducerBot
    token: --
    offset: 10
    limit: 100
    timeout: 50
  sensor:
    thresold-level: 160
    sleep-time: 100